#!/usr/bin/env bash

# These must also be updated in build.xml
version=0.5.1
# changing meteor version with the latest 1.5 version
meteor_version=1.5

scriptDir=$(dirname $0)
libDir=$scriptDir/lib
meteorPath=$libDir/meteor-$meteor_version
# The new meteor occurs as a tar.gz file.
meteorUrl=http://www.cs.cmu.edu/~alavie/METEOR/download/meteor-${meteor_version}.tar.gz

meteorJar=$meteorPath/meteor-${meteor_version}.jar
terJar=$scriptDir/lib/tercom-0.8.0.jar
